import React, { useRef, useState } from "react";
import html2pdf from "html2pdf.js";
import axios from "axios";
import { useAuth } from "../context/AuthContext";

const AgreementForm = () => {
  const { user } = useAuth();

  const [formData, setFormData] = useState({
    landlord: "",
    property: "",
    rent: "",
    startDate: "",
    endDate: "",
  });

  const [submitted, setSubmitted] = useState(false);
  const pdfRef = useRef();

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleGeneratePDF = () => {
    const element = pdfRef.current;

    const opt = {
      margin: 0.5,
      filename: "rental_agreement.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
    };

    html2pdf().set(opt).from(element).save();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user) return;

    const payload = {
      ...formData,
      tenant: user.email,
    };

    try {
      const res = await axios.post(`${import.meta.env.VITE_API_URL}/api/agreements`, payload);
      console.log("Agreement saved:", res.data);
      setSubmitted(true);
    } catch (err) {
      console.error("Error saving agreement:", err);
    }
  };

  return (
    <div className="bg-white p-6 rounded shadow-md max-w-xl mx-auto mt-6">
      <h2 className="text-2xl font-bold mb-4 text-blue-700">📄 Create Rental Agreement</h2>

      <form onSubmit={handleSubmit} className="space-y-3">
        {["landlord", "property", "rent", "startDate", "endDate"].map((field) => (
          <input
            key={field}
            type={field.includes("Date") ? "date" : field === "rent" ? "number" : "text"}
            name={field}
            value={formData[field]}
            onChange={handleChange}
            required
            placeholder={field.charAt(0).toUpperCase() + field.slice(1)}
            className="w-full border px-3 py-2 rounded"
          />
        ))}
        <button
          type="submit"
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          Save Agreement
        </button>
      </form>

      {submitted && (
        <>
          <div
            ref={pdfRef}
            style={{
              padding: "20px",
              marginTop: "30px",
              backgroundColor: "#f8f8f8",
              color: "#000",
              border: "1px solid #ccc",
              borderRadius: "5px",
              fontFamily: "Arial, sans-serif",
            }}
          >
            <h3 style={{ fontSize: "20px", marginBottom: "10px" }}>📜 Rental Agreement</h3>
            <p><strong>Landlord:</strong> {formData.landlord}</p>
            <p><strong>Tenant:</strong> {user.email}</p>
            <p><strong>Property:</strong> {formData.property}</p>
            <p><strong>Rent:</strong> ₹{formData.rent} per month</p>
            <p><strong>Start Date:</strong> {formData.startDate}</p>
            <p><strong>End Date:</strong> {formData.endDate}</p>
            <p style={{ marginTop: "10px", fontStyle: "italic" }}>Generated by SmartRentals</p>
          </div>

          <button
            onClick={handleGeneratePDF}
            className="mt-4 bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700"
          >
            Download PDF
          </button>
        </>
      )}
    </div>
  );
};

export default AgreementForm;
